// <auto-generated />
using System;
using DesafioVaiVoa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioVaiVoa.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210528200638_version2")]
    partial class version2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioVaiVoa.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PessoaIdPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaIdPessoa");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("DesafioVaiVoa.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("IdPessoa");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("DesafioVaiVoa.Models.Card", b =>
                {
                    b.HasOne("DesafioVaiVoa.Models.Pessoa", "Pessoa")
                        .WithMany("ListCards")
                        .HasForeignKey("PessoaIdPessoa");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("DesafioVaiVoa.Models.Pessoa", b =>
                {
                    b.Navigation("ListCards");
                });
#pragma warning restore 612, 618
        }
    }
}
